name: Maven Test

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'  # Specify the distribution type
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ github.token }}
          overwrite-settings: true

      - name: Build and test with Maven
        run: mvn clean test
